name: "Deploy your FastAPI documentation on Bump.sh"

on:
  push: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: "install python dependencies"
        run: "pip install -r requirements.txt"
      - name: "generate openapi files"
        run: "python3 apicontract.py main:app"
      - name: "Send Openapi definition to Bump.sh"
        uses: bump-sh/github-action@v1
        with:
          file: openapi.yaml
          command: "preview"
