name: "Deploy your FastAPI documentation on Bump.sh"

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: "install python dependencies"
        run: "pip install -r requirements.txt"
      - name: "generate openapi files"
        run: "python3 apicontract.py"
      - name: "Send Openapi definition to Bump.sh"
        uses: bump-sh/github-action@v1
        with:
          file: openapi.yaml
          doc: ${{secrets.BUMP_DOC_SLUG}}
          token: ${{secrets.BUMP_DOC_TOKEN}}
